- name: Install required libs for Brave
  become: true
  apt:
    name: ["curl", "apt-transport-https"]
  tags: &tags_brave_tasks [ 'brave', 'desktop', 'browsers']

- name: Brave Browser gpg key download
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
  tags: *tags_brave_tasks

- name: Brave Browser PPA Setting
  become: true
  shell:  echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list
  tags: *tags_brave_tasks

- name: Brave Browser Installation
  become: true
  apt:
    update_cache: yes
    name: brave-browser
  tags: *tags_brave_tasks
