- name: obs ppa (ppa:obsproject/obs-studio)
  become: true
  apt_repository:
    repo: ppa:obsproject/obs-studio
    update_cache: True
  tags:
    - desktop
    - productivity

- name: Install packages
  become: true
  apt:
    name: [ "gimp", "shutter", "ffmpeg", "obs-studio" ]
  tags:
    - desktop
    - productivity
