- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "/home/{{ user }}/.nvm/nvm.sh"
  tags:
    - install
    - programming-languages
    - nodejs

- name: Install Node LTS
  become: yes
  become_user: "{{ user }}"
  shell: source ~/.nvm/nvm.sh && nvm install --lts
  args:
    executable: /bin/bash
  tags:
    - install
    - programming-languages
    - nodejs

