- hosts: localhost
  vars:
    user: "zrie"
  pre_tasks:
  - name: Update apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
  tasks:
    - include: tasks/zsh.yml
    - include: tasks/core-setup.yml
    - include: tasks/programming-languages/nasm.yml
    - include: tasks/programming-languages/python.yml
    - include: tasks/programming-languages/rust.yml
    - include: tasks/programming-languages/nvm-node.yml
    - include: tasks/programming-languages/ts-npm-packages.yml
    - include: tasks/neovim.yml
    - include: tasks/lunar-nvim.yml
    - include: tasks/lazy-nvim.yml
    - include: tasks/desktop/productivity-apps.yml
    - include: tasks/desktop/browsers.yml
    - include: tasks/desktop/window-manager.yml
