- name: Install ZSH
  apt: name=zsh
  tags: &tags_zsh_tasks [ 'install', 'core', 'dotfiles', 'zsh']

- name: Change Shell
  shell: chsh -s $(which zsh)
  tags: *tags_zsh_tasks

- name: Check that some configuration exists
  stat:
    path: "/home/{{ user }}/.oh-my-zsh"
  register: omz_stats
  tags: *tags_zsh_tasks

- name: Install oh-my-zsh
  shell: curl -L https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh > /tmp/.omz-installer && chmod +x /tmp/.omz-installer && /tmp/.omz-installer
  when: omz_stats.stat.exists == False
  become_user: "{{ user }}"
  tags: *tags_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_zsh_tasks
